sanity checks; no removing and installing at the same time

diff --git a/fpkg b/fpkg
--- a/fpkg
+++ b/fpkg
@@ -110,11 +110,21 @@ while getopts ":hfi:r:" option; do
 	f) fast="ye" ;; #apparently only works if passed before -h (like -f -h or -fh)
 	h) Help ;;
 	i)
+		install=true
 		package=${OPTARG}
+		if $install && $remove; then
+			echo "Yue can't install (-i) and remove (-r) at the same time, duh1!!1!1" 1>&2
+			exit 1
+		fi
 		Install ${package}
 		;;
 	r)
+		remove=true
 		package=${OPTARG}
+		if $install && $remove; then
+			echo "Yue can't install (-i) and remove (-r) at the same time, duh1!!1!1" 1>&2
+			exit 1
+		fi
 		Remove ${package}
 		;;
 	\?) Help ;;
