Update fpkg
change $yesno to $reply for easier

also fixed some shit i did wrong, my bad

diff --git a/fpkg b/fpkg
--- a/fpkg
+++ b/fpkg
@@ -12,13 +12,13 @@ fpkg_ver="0.1-r1"
 
 #Takes error message as first parameter; used as: command || exit_with_error <MSG>
 function exit_with_error() {
-	echo "FATAL: $1"
-	echo "Abortin'."
+	echo " !! Error !! $1"
+	echo " !! Abort !! "
 	exit 1
 }
 
 function warn() {
-	echo "WARNING: $1"
+	echo " !! Warn !! $1"
 }
 
 function sleepy() {
@@ -40,11 +40,11 @@ function remover() {
 	# shellcheck disable=SC2034
 	countdown 3 ' !! Removing in'
 	if [[ -d /usr/bin/"${package}" ]]; then
-		rm -r /usr/bin/"${package:?}" || exit_with_error "!! Error !! Couldn't remove package."
+		rm -r /usr/bin/"${package:?}" || exit_with_error "Couldn't remove package."
 	elif [[ -f /usr/bin/"${package}" ]]; then
-		rm /usr/bin/"${package}" || exit_with_error "!! Error !! Couldn't remove package."
+		rm /usr/bin/"${package}" || exit_with_error "Couldn't remove package."
 	else
-		echo " !! Error !! How 'bout yue install that package first?"
+		echo "How 'bout yue install that package first?"
 		exit 1
 	fi
 	echo "!! Packages removed!!1 :)"
@@ -88,7 +88,7 @@ function cleanup() {
 function Install() {
 	if [ "$remove" = true ]; then
 		echo ""
-		echo "!! Error !! Already removed sumthin', ain't gonna install that"
+		echo "Already removed sumthin', ain't gonna install that"
 		exit 0
 	else
 		echo " :: Searchin' for package ..."
@@ -97,7 +97,7 @@ function Install() {
 		 echo " !! Package finded."
   else
    echo " !! Package ${package} not found."
-			echo " !! ABORTIN'"
+			echo " !! Abort !!"
 			return 1
 		fi
 
@@ -125,8 +125,8 @@ function Install() {
 				chmod 755 -R /tmp/fpkg-cache
 			fi
 			mkdir /tmp/fpkg-cache/"${package}"
-			cd /tmp/fpkg-cache/"${package}" || exit_with_error "!! Error !! Could not cd to '/tmp/fpkg-cache/${package}'"
-			wget "${repoURL}${package}" >/dev/null 2>&1 || warn "!! Error!! Could not fetch package ${package}. Skippin'."
+			cd /tmp/fpkg-cache/"${package}" || exit_with_error "Could not cd to '/tmp/fpkg-cache/${package}'"
+			wget "${repoURL}${package}" >/dev/null 2>&1 || warn "Could not fetch package ${package}. Skippin'."
 			return 2
 
 			if [ "$downloadonly" = true ]; then
@@ -141,13 +141,13 @@ function Install() {
 				#Handle .sh scripts and .fpkg files differently
 				case $(file --mime-type -b "${package}") in
 				*shellscript*)
-					mv "/tmp/fpkg-cache/${package}" /usr/bin || exit_with_error "Could not unpack executables. Sry."
+					mv "/tmp/fpkg-cache/${package}" /usr/bin || exit_with_error "Could not unpack executables. My bad."
 					sleepy 2
 					chmod +x "/usr/bin/${package}"
 					;;
 				application/gzip)
 					mkdir /tmp/fpkg-cache/"${package}-cache"
-					tar -xzvf /tmp/fpkg-cache/"${package}" -O /tmp/fpkg-cache/"${package}-cache" || exit_with_error "Could not unpack executables. Sry."
+					tar -xzvf /tmp/fpkg-cache/"${package}" -O /tmp/fpkg-cache/"${package}-cache" || exit_with_error "Could not unpack executables. My bad."
 					find . -print0 | while IFS= read -r -d'' f; do
 						file -ib "$f" | grep shellscr && mv "$f" /usr/bin
 						chmod +x "/usr/bin/$f"
@@ -170,7 +170,7 @@ function Install() {
 function Remove() {
 	if [ "$install" = true ]; then
 		echo ""
-		echo "!! Error !! Already installed sumthin', ain't gonna remove that"
+		echo "Already installed sumthin', ain't gon remove that"
 		exit 0
 	else
 		echo " :: Lookin' in /usr/bin ..."
@@ -179,8 +179,8 @@ function Remove() {
 		sleepy 0.5
 		echo "These packages gon be DELETED:"
 		pkginfo
-		read -rp "Are you sure you wanna get rid of these packages? [y/n]: " yesno
-		case "$yesno" in
+		read -rp "Are you sure you wanna get rid of these packages? [y/n]: " reply
+		case "$reply" in
 		[nN])
 			echo " !! Didn't do jack shit..."
 			;;
@@ -194,11 +194,11 @@ function Remove() {
 function ConfClean() {
 	# shellcheck disable=SC2140
 	if [[ -d "$HOME"/.config/"${package}*" ]]; then
-		rm -r "$HOME"/.config/"${package}*" || exit_with_error "!! Error!! Couldn't remove config."
+		rm -r "$HOME"/.config/"${package}*" || exit_with_error "Couldn't remove config."
 	elif [[ -f "$HOME"/.config/"${package}*" ]]; then
-		rm "$HOME"/.config/"${package}*" || exit_with_error "!! Error !! Couldn't remove config."
+		rm "$HOME"/.config/"${package}*" || exit_with_error "Couldn't remove config."
 	else
-		echo " !! Error !! Sum'n went wrong while removin' that config, my bad."
+		echo "Sum'n went wrong while removin' that config, my bad."
 		exit 1
 	fi
 }
@@ -216,8 +216,8 @@ function Purge {
 	sleepy 0.5
 	echo "These packages gon be PURGED:"
 	pkginfo
-	read -rp "Are you sure you wanna get rid of these packages? [y/n]: " yesno
-	case "$yesno" in
+	read -rp "Are you sure you wanna get rid of these packages? [y/n]: " reply
+	case "$reply" in
 	[nN])
 		echo " !! Didn't do jack shit..."
 		;;
@@ -235,17 +235,17 @@ function Purge {
 
 #Check for root privileges
 if [ "$EUID" -ne 0 ]; then
-	exit_with_error "!! Error !! Yue gon need root for this dumbass."
+	exit_with_error "Yue gon need root for this dumbass."
 fi
 
-[[ -d /etc/fpkg/ ]] || mkdir /etc/fpkg/ || exit_with_error "!! Error !! Could not create '/etc/fpkg/'"
-chmod 755 /etc/fpkg/ || exit_with_error "!! Error!! Could not chmod '/etc/fpkg/'"
+[[ -d /etc/fpkg/ ]] || mkdir /etc/fpkg/ || exit_with_error "Could not create '/etc/fpkg/'"
+chmod 755 /etc/fpkg/ || exit_with_error "Could not chmod '/etc/fpkg/'"
 
-[[ -d /etc/fpkg/packages/ ]] || mkdir /etc/fpkg/packages/ || exit_with_error "!! Error !! Could not create '/etc/fpkg/packages/'"
-chmod 755 /etc/fpkg/packages/ || exit_with_error "!! Error !! Could not chmod '/etc/fpkg/packages/'"
+[[ -d /etc/fpkg/packages/ ]] || mkdir /etc/fpkg/packages/ || exit_with_error "Could not create '/etc/fpkg/packages/'"
+chmod 755 /etc/fpkg/packages/ || exit_with_error "Could not chmod '/etc/fpkg/packages/'"
 
-[[ -d /etc/fpkg/repositories/ ]] || mkdir /etc/fpkg/repositories/ || exit_with_error "!! Error !! Could not create '/etc/fpkg/repositories/'"
-chmod 755 /etc/fpkg/repositories/ || exit_with_error "!! Error !! Could not chmod '/etc/fpkg/repositories/'"
+[[ -d /etc/fpkg/repositories/ ]] || mkdir /etc/fpkg/repositories/ || exit_with_error "Could not create '/etc/fpkg/repositories/'"
+chmod 755 /etc/fpkg/repositories/ || exit_with_error "Could not chmod '/etc/fpkg/repositories/'"
 
 optlist=':hfi:r:vdp:c:' #add new opts here
 
